CREATE TABLE TARJETA_EXT(
    id NUMBER PRIMARY KEY,
    tipo CHAR NOT NULL,
    Numero_Tarjeta NUMBER(16,0) NOT NULL,
    moneda CHAR NOT NULL,
    monto_limite DECIMAL NOT NULL,
    Dia_corte NUMBER,
    Dia_pago NUMBER,
    Tasa_interes DECIMAL NOT NULL,
    fecha_expedicion DATE NOT NULL,
    id_cliente NUMBER NOT NULL REFERENCES CLIENTE(id),
    id_tipo_tarjeta NUMBER NOT NULL REFERENCES TIPOTARJETA(id),
    creation_date DATE DEFAULT SYSDATE,
    Data_Update DATE DEFAULT SYSDATE,
    id_tpadre NUMBER NOT NULL REFERENCES TARJETA(id)

);

CREATE SEQUENCE seq_tarjeta_ext START WITH 1 INCREMENT BY 1;

--INSERT INTO TARJETA (tipo, NUMERO_TARJETA, MONEDA, MONTO_LIMITE, DIA_CORTE, DIA_PAGO, TASA_INTERES, FECHA_EXPEDICION,
--ID_CLIENTE, ID_TIPO_TARJETA) VALUES('C',1234567891023456,'Q', 5000, 17, 10, 6, '01-01-2030',  )