CREATE TABLE TIPOCLIENTE(
    id NUMBER PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    descripcion VARCHAR2(200) NOT NULL
);

CREATE TABLE TIPOCUENTAS(
    id NUMBER PRIMARY KEY,
    nombre VARCHAR(35) NOT NULL,
    descripcion VARCHAR2(105) NOT NULL 
);

CREATE TABLE TIPOTARJETA(
    id NUMBER PRIMARY KEY,
    nombre VARCHAR(35) NOT NULL
);
-- Falta agregar tipo de servicio
CREATE TABLE TIPODEPAGO(
    id NUMBER PRIMARY KEY,
    nombre VARCHAR(10) NOT NULL
);

CREATE TABLE TIPOSEGURO(
    id NUMBER PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL
);

CREATE TABLE TIPOTRANSACCION(
    id NUMBER PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL
);

CREATE TABLE TIPOREMESA(
    id NUMBER PRIMARY KEY,
    nombre VARCHAR(10)
);
-- TIPOPREMIO pendiente

CREATE TABLE TIPONOTIFICACION(
    id NUMBER PRIMARY KEY,
    nombre VARCHAR(10) NOT NULL
);

CREATE TABLE ACCESOS(
    id NUMBER PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    pass VARCHAR(100) NOT NULL
);
